### ISSUE TITLE
Fragment VoiceSenderDialog not attached to an activity.

### ISSUE THREAD

**Issue by vedraj360** [AsynctaskCoffee/VoiceRecorder#3]
I am having a issue that It just records for 1 second and the it stops recording. And the uri path is also null. can you help me out.

I am using bottom sheet dialog 
 new VoiceSenderDialog(this).show(getSupportFragmentManager(), "VOICE");

  java.lang.IllegalStateException: Fragment VoiceSenderDialog{b1bef6a} (f0b82165-1ae6-4a05-9e4f-c0fef4ba5a4c) not attached to an activity.
        at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)

**Comment by AsynctaskCoffee** [comment]
Are you using this in fragment or activity ?

**Comment by AsynctaskCoffee** [comment]
And will you provide your target version ?

**Comment by vedraj360** [comment]
I was using this for android 11 and it was not working so I forked the library and made the changes for android 11. I can open a PR if you want.

**Comment by AsynctaskCoffee** [comment]
Please send the PR :) Thank you.

**Comment by AsynctaskCoffee** [comment]
I will add your name in readme

**Comment by vedraj360** [comment]
@AsynctaskCoffee  Done you can check the PR.

**Comment by AsynctaskCoffee** [comment]
Thanks bro <3
